name: Build Docker Images

on:
  workflow_dispatch:
  push:
    tags: [ '*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
          docker.io/${{ github.repository }}
        tags: |
          ${{ vars.GITHUB_REF_NAME }}
          latest

    - name: Download Source Codes
      run: >-
        set -xe
        && mkdir -p sources/
        && wget https://tengine.taobao.org/download/tengine-${{ vars.TENGINE_VERSION }}.tar.gz -O sources/tengine-${{ vars.TENGINE_VERSION }}.tar.gz
        && wget https://github.com/google/ngx_brotli/archive/refs/tags/v${{ vars.BROTLI_VERISON }}.tar.gz -O sources/ngx_brotli-${{ vars.BROTLI_VERISON }}.tar.gz
        && wget https://github.com/nginx-modules/ngx_cache_purge/archive/refs/tags/${{ vars.NGX_CACHE_PURGE_VERSION }}.tar.gz -O sources/ngx_cache_purge-${{ vars.NGX_CACHE_PURGE_VERSION }}.tar.gz

    - uses: docker/build-push-action@v5
      name: Build the Docker image
      with:
        context:   .
        pull:      true
        push:      true
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        tags:      ${{ steps.meta.outputs.tags }}
        labels:    ${{ steps.meta.outputs.labels }}
        build-args: |
          NGINX_UI_VERSION=${{ vars.GITHUB_REF_NAME }}
          BUILD_THREADS=1
          TENGINE_VERSION=${{ vars.TENGINE_VERSION }}
          BROTLI_VERISON=${{ vars.BROTLI_VERISON }}
          NGX_CACHE_PURGE_VERSION=${{ vars.NGX_CACHE_PURGE_VERSION }}
          TENGINE_BUILDFLAG=${{ vars.TENGINE_BUILDFLAG }}
